[workspace]
resolver = "3"
members = ["server", "client", "chat-lib"]

[package]
name = "lesson_9"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
server = { path = "./server" }
client = { path = "./client" }
yansi = "1.0.1"
