[package]
name = "chat-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
anyhow = "1.0.96"
yansi = "1.0.1"
