[package]
name = "lesson_9"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
bincode = "1.3.3"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
